<#
.SYNOPSIS
    Records the battery report from powercfg
.DESCRIPTION
    Records the battery report html files generated by powercfg /batteryreport
#>
function Checkpoint-BatterReport(
    [string] $DestinationFolder = "$Home\Data\Battery-Report"
) {

    # Create the powercfg battery report
    powercfg /batteryreport

    # Move the report from the source directory to the desired destination
    $Source = "$PSScriptRoot\battery-report.html" # This is where powercfg outputs the battery-report
    $Destination = Join-Path -Path $DestinationFolder -ChildPath "$(Get-Date -Format FileDate)_battery-report.html"
    Move-Item -Path $Source -Destination $Destination

    Write-Host "battery-report.html moved to $Destination"

}

# Record the powercfg battery report
Checkpoint-BatterReport
