<#
.SYNOPSIS
    Records the battery report from powercfg
.DESCRIPTION
    Records the battery report html files generated by powercfg /batteryreport
#>

[CmdletBinding()]
Param (
    # Specifies the destination folder where the battery report will be saved. Default is "$Home\Data\Battery-Report".
    [Parameter(ValueFromPipeline, ValueFromPipelineByPropertyName, Position = 0)]
    [Alias("Destination", "Path", "Store")]
    [string] $DestinationFolder = "$Home\Data\Battery-Report"
) 

Process {

    # Check if the destination folder exists, if not create it
    if (!(Test-Path $DestinationFolder)) {
        New-Item -ItemType Directory -Force -Path $DestinationFolder | Out-Null
    }

    # Go to the destination folder
    Set-Location -Path $DestinationFolder

    try {
    
        # Create the powercfg battery report
        powercfg /batteryreport

        # Rename the generated battery-report.html file to include the current date
        $Name = "$(Get-Date -Format yyyyMMdd)_battery-report.html"
        Rename-Item -Path ".\battery-report.html" -NewName $Name -Force

        # Write the log the successful report
        $logMessage = "Battery Report Generated: $Name"
        Write-Host "✅ $logMessage ✅"
        $logMessage = "$(Get-Date -Format "yyyy-MM-dd HH:mm:ss") --- $logMessage"
        $logMessage | Out-File -FilePath ".\battery-report.log" -Append
    
    }
    catch {
    
        # Write and log the error message
        Write-Error "❌ An error occurred: $($_.Exception.Message) ❌"
        $_.Exception.Message | Out-File -FilePath ".\battery-report.log" -Append

    
    }
}
